### ISSUE TITLE
Add Channel text or logo in favorites

### ISSUE THREAD

**Issue by spoelly** [jjtbsomhorst/eu.jeroensomhorst.tvgids#4]
Currently all favorites are listed but the channel is not. Please add it as text or as a logo.

**Comment by jjtbsomhorst** [comment]
So you want to see the channel where the favorite is from on the favorites list. Logo's can't be used unfortunately.

**Comment by jjtbsomhorst** [comment]
This is fixed in the next beta release (0.0.6)
