### ISSUE TITLE
Saturday and sunday are missing

### ISSUE THREAD

**Issue by Inversion-NL** [jjtbsomhorst/eu.jeroensomhorst.tvgids#5]
Saterday and sunday are missing from the channels list.

**Comment by jjtbsomhorst** [comment]
The days you see in the list are 2 days before and 2 days after the current day. So on wednesday you would see Monday, Tuesday, Wednesday, Thursday, Friday.

**Comment by Inversion-NL** [comment]
Ok.
But why only 2 days ahead and 2 days back?
How am I supposed to add a favorite for next Saturday?
Why would I want to schedule for one or two days back? Or will it schedule them for next week?

Other than that: great idea, don't get me wrong. Love your app and just trying to help you through the Beta :-)
