### ISSUE TITLE
Error while selecting channel

### ISSUE THREAD

**Issue by Inversion-NL** [jjtbsomhorst/eu.jeroensomhorst.tvgids#7]
Error while selecting channel in a flow.
Don't know if you need more info like favorites or channel mappings?

![image](https://cloud.githubusercontent.com/assets/15921016/26157906/b33eed96-3b1a-11e7-9652-807e2eda5960.png)

**Comment by jjtbsomhorst** [comment]
Which firmware version is your homey using?
Do you have any favorites ( when you open the settings and go to favorites do you see any?)

**Comment by Inversion-NL** [comment]
1.3.0 rc7
Yes, I have two favorites:
![image](https://cloud.githubusercontent.com/assets/15921016/26160349/50e2e998-3b21-11e7-9892-75942d55328b.png)

**Comment by jjtbsomhorst** [comment]
This should be fixed in beta 0.0.5

**Comment by Inversion-NL** [comment]
Great work
